FROM python:latest

WORKDIR /phamhoan/micro-4

COPY . /phamhoan/micro-4

RUN pip3 install flask

RUN pip install requests

ENV FLASK_APP=app.py

CMD ["flask", "run", "--debug", "--host=0.0.0.0", "--port=5003"]